apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080
      name: default
      targetPort: 8080
      nodePort: 30001
    - port: 50000
      protocol: TCP
      targetPort: 50000
      name: agents
      nodePort: 30002

